FROM nginx:latest

# Path Linux: /usr/share/nginx/html
# COPY /sitio /usr/share/nginx/html 

# Path Windows: /usr/share/nginx/sitio
COPY /sitio /usr/share/nginx/html/sitio

# Volumes
# VOLUME [ "/sitio", "/usr/share/nginx/html" ]
