FROM nginx:latest

# En linux
# COPY /sitio /usr/share/nginx/html  

# En Windows
COPY /sitio /usr/share/nginx/html/sitio 

# Volumes
VOLUME [ "D:/PROJECTS/learning-docker/projects/clase-11-2/sitio", "/usr/share/nginx/html/sitio" ]